[package]
name = "test_dylib_module"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "test_dylib_module"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rhai-dylib = { version = "=0.6.0", features = ["sync"] }
rustler = "0.36.0"
